# Generated by Django 4.0.2 on 2022-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLU', 'Blue'), ('YEL', 'Yellow'), ('BLA', 'Black'), ('WHI', 'White')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='fuel',
            field=models.CharField(choices=[('DIE', 'Diesel'), ('PET', 'Petrol'), ('HYB', 'Hybrid'), ('LPG', 'LPG'), ('ELE', 'Electric')], max_length=3),
        ),
    ]
