# Generated by Django 4.0.2 on 2022-02-06 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cardetail_color_alter_cardetail_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
